function [fail,disps,ts,te] =fem_sim_slope_solver(srf,vert,tria,tnum,prop)
% output the FEM simulation result
nnode=size(vert,1);
nelement=length(tnum);
node=vert;
etype=tnum;
%% get the constraint node
% get the bottom
t=node(:,2);
s=(t<=0.1);id=1:1:nnode;
sid=s.*id';sid(sid==0)=[];
bottom=sid;
% get the left
t=node(:,1);
s=(t<=0.1);id=1:1:nnode;
sid=s.*id';sid(sid==0)=[];
left=sid;
% get the right
t=node(:,1);
% s=(abs(t-w1-s1-w2)<0.1);id=1:1:nnode;
s=(abs(t-max(t))<0.1);id=1:1:nnode;
sid=s.*id';sid(sid==0)=[];
right=sid;
% form nf [node_number x_fix y_fix]
nr=ones(length(right)+length(left)+length(bottom),3);
nr(1:length(bottom),1)=bottom; nr(1:length(bottom),2:3)=0;
nr(length(bottom)+1:length(bottom)+length(left)+length(right),1)=[left;right];
nr(length(bottom)+1:length(bottom)+length(left)+length(right),2)=0;
% etype=tnum;
ndim=2;nodof=2;nod=3;element='triangle' ;
nip=1;
nels=nelement;
nn=nnode;
g_coord=node';
g_num=[tria(:,1),tria(:,3),tria(:,2)]';
nf=ones(nodof,nn);
for i=1:size(nr,1)
    nf(:,nr(i,1))=nr(i,2:nodof+1);
end
nf=formnf(nf);
neq=max(nf(:));

ndof=nod*nodof; % number of free dofs
g_g=zeros(ndof,nels); %

% ! -----------------------loop the elements to find global arrays sizes-----
for iel=1:nels
    %     if mod(iel,100000)==0
    %         disp(num2str(iel));
    %     end
    num=g_num(:,iel);
    [ g ] = num_to_g(num,nf);
    g_num(:,iel)=num;
    g_g(:,iel)=g ;
    %     kdiag = fkdiag(kdiag, g);
end
% calculate node force
gravlo=zeros(neq,1); %node force generated by gravity
[points, weights]= sample(element,nip );

KK=sparse(neq,neq);
interval=100000;
% t1=mod(nels,interval);
ih=4;
I=zeros(100000000,1);J=I;K=I;idx=0;
for iel=1:nels
    if mod(iel,interval)==0 % This section can svae memory
        KM=sparse(I(1:idx,:),J(1:idx,:),K(1:idx,:),neq,neq);
        KK=KK+KM;
        I=zeros(100000000,1);J=I;K=I;idx=0;
    end
        eld=zeros(ndof,1);
        dee=deemat(prop(5,etype(iel)),prop(6,etype(iel)),ih);
        num=g_num(:,iel);
        coord=g_coord(:,num)';
        g=g_g(:,iel);
        km=zeros(ndof,ndof);
        % gauss integration
        for i=1:nip
            fun=shape_fun(points,i,ndim,nod);
            der=shape_der(points,i,ndim,nod);
            jac=der*coord;
            Det=det(jac);
            deriv=jac\der;
            bee=beemat( deriv,ih);
            km=km+bee'*dee*bee*Det*weights(i);
            eld(nodof:nodof:ndof)=eld(nodof:nodof:ndof)+fun(:)*Det*weights(i);
        end
         for i=1:ndof
            if g(i)~=0
                gravlo(g(i))=gravlo(g(i))-eld(i)*prop(4,etype(iel));
                for j=1:ndof
                    if g(j)~=0
                        idx=idx+1;
                        I(idx)=g(i);J(idx)=g(j);K(idx)=km(i,j);
                    end
                end
            end
         end
end
KM=sparse(I(1:idx,:),J(1:idx,:),K(1:idx,:),neq,neq);
KK=KK+KM;


% disp('end loop');
% loads=zeros(neq,1);
% loads=loads+gravlo;
% loads= cholmod2(KK,loads);
% disp('finish mechanical calculation');
% % loads(abs(loads)<1e-10)=0;
% disps=zeros(nn,nodof);
zero=0;two=2; dt=1.0e15;d3=3.0;d4=4.0;d6=6;one=1.0;%nprops=6;
penalty=1e20;start_dt=1.e15;nst=4;
ndim=2;
penalty=1e20;start_dt=1.e15;nst=4;
iy=1;
np_types=2;
dt=start_dt;tol=1e-4;limit=1000;
    tensor_stress=zeros(nst,nip,nels);
    tensor_strain=zeros(nst,nip,nels);
for i=1:np_types
    phi=prop(1,i);
    tnph=tan(phi*pi/180);
    phif=atan(tnph/srf(iy));
    snph=sin(phif) ;
    e=prop(5,i) ;
    v=prop(6,i);
    ddt=4*(1+v)*(1-2*v)/(e*(1-2*v+snph^2));
    if ddt<dt
        dt=ddt;
    end
end
    iters=0;
    bdylds=zeros(neq,1);
    evpt=zeros(nst,nip,nels);
    oldis=zeros(neq,1);
    iterk=0;
    %-----------------------plastic iteration loop----------------------------
    while 1

        fmax=0;
        iters=iters+1 ;
        loads=gravlo+bdylds ;
        loads= cholmod2(KK,loads);
        tensor=zeros(nst,nip,nels);
        if (iy==1 && iters==1)
            elastic=loads;
        end
        % !-----------------------check plastic convergence-------------------------
        [converged,oldis,res] = checon(loads,oldis,tol);
                iterk=iterk+1;
        disp(['iteration is  ',num2str(iterk),'  error is ',num2str(res) ]);
        if iters==1
            converged=0;
        end
        if converged==1 || iters==limit
            bdylds=zeros(neq,1);
        end
        % !-----------------------go round the Gauss Points -----------------------
        for iel=1:nels %elements_3
%             if etype(iel)==1
            bload=zeros(ndof,1);
            phi=prop(1,etype(iel));
            tnph=tan(phi*pi/180);
            phif=atan(tnph/srf(iy))*180/pi ;
            psi=prop(3,etype(iel));
            tnps=tan(psi*pi/180) ;
            psif=atan(tnps/srf(iy))*180/pi;
            cf=prop(2,etype(iel))/srf(iy) ;
            e=prop(5,etype(iel)) ;
            v=prop(6,etype(iel)) ;
            dee = deemat(e,v,nst);
            rload=zeros(ndof,1);% 
            num=g_num(:,iel);
            coord=g_coord(:,num)';
            g=g_g(:,iel);
            eld=zeros(length(g),1);
            for ii=1:length(g) %eld=loads(g) 
                if g(ii)~=0
                    eld(ii)=loads(g(ii));
                else
                    eld(ii)=0;
                end
            end
            for i=1:nip %gauss_pts_4
                der=shape_der(points,i,ndim,nod);
                jac=der*coord;
                Det=det(jac);
                deriv=jac\der;
                bee=beemat( deriv,nst );
                eps=bee*eld;
                tensor_strain(:,i,iel)=eps;
                eps=eps-evpt(:,i,iel);
                sigma=dee*eps;
                stress=sigma;%+tensor(:,i,iel) ;
                tensor_stress(:,i,iel)=stress;
                [sigm,dsbar,lode_theta]=invar(stress);
                %  !-----------------------check whether yield is violated-------------------
                f=mocouf(phif,cf,sigm,dsbar,lode_theta);
                if converged==1 && iters==limit
                    devp=stress;
                else
                    if f>=zero
                        [dq1,dq2,dq3]=mocouq(psif,dsbar,lode_theta);
                        [m1,m2,m3]= formm(stress);
                        flow=f*(m1*dq1+m2*dq2+m3*dq3);
                        erate=flow*stress;
                        evp=erate*dt;
                        evpt(:,i,iel)=evpt(:,i,iel)+evp;
                        devp=dee*evp;
                    end
                end
                if f>=0 || (converged==1 || iters==limit)
                    eload=bee'*devp;
                    bload=bload+eload*Det*weights(i);
                end
            end
%             if etype(iel)==2 && f>0
%                 disp('rock is failure');
%             end
            % !-----------------------compute the total bodyloads vector----------------
            for jj=1:length(g)
                if g(jj)~=0
                    bdylds(g(jj))=bdylds(g(jj))+bload(jj);
            % react(g(jj))=react(g(jj))+rload(jj);
                end
            end
%         end
        end %elements_3
        if converged==1 || iters==limit
            break;
        end
    end
if iters==limit
    fail=1;
else
    fail=0;
end
disps=zeros(nn,nodof);        
for i=1:nn
    for j=1:nodof
        if nf(j,i)==0
            disps(i,j)=0;
        else
            disps(i,j)=loads(nf(j,i));
        end
    end
end
ts=zeros(nst,nels);
te=zeros(nst,nels);
for i=1:nels
    for j=1:nip
        ts(:,i)=ts(:,i)+tensor_stress(:,j,i);
        te(:,i)=te(:,i)+tensor_strain(:,j,i);
    end
end
ts=ts/nip;
te=te/nip;
% nod_stress=zeros(nst,nn);
% nod_strain=zeros(nst,nn);
% num_repeat=zeros(1,nn);
% for iel=1:nels
%     num=g_num(:,iel);
%     nod_stress(:,num(1))=nod_stress(:,num(1))+tensor_stress(:,1,iel)/3;
%     nod_stress(:,num(2))=nod_stress(:,num(2))+tensor_stress(:,1,iel)/3;
%     nod_stress(:,num(3))=nod_stress(:,num(3))+tensor_stress(:,1,iel)/3;
%     nod_strain(:,num(1))=nod_strain(:,num(1))+tensor_strain(:,1,iel)/3;
%     nod_strain(:,num(2))=nod_strain(:,num(2))+tensor_strain(:,1,iel)/3;
%     nod_strain(:,num(3))=nod_strain(:,num(3))+tensor_strain(:,1,iel)/3;
%     for i=1:length(num)
%         num_repeat(num(i))=num_repeat(num(i))+1;
%     end
% end
% 
% nod_stress=nod_stress./num_repeat;
% nod_strain=nod_strain./num_repeat;
% ts=nod_stress;
% te=nod_strain;
end

